# Generated by Django 3.1.1 on 2020-09-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200906_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='17 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=17, verbose_name='ISBN'),
        ),
    ]
