# Generated by Django 3.1.1 on 2020-09-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200912_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='action_time',
            field=models.CharField(help_text='Enter the time of action', max_length=10, null=True),
        ),
    ]
