# Generated by Django 3.1.1 on 2020-09-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_action_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='action_time',
            field=models.CharField(help_text='Enter the time of action', max_length=20, null=True),
        ),
    ]
